/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package btc.wallet.finder;

import org.junit.Test;

public class ApplicationTest {
  @Test
  public void testSomeLibraryMethod() {

  }
}
